const mockTasks = [
  {
    id: '1',
    category: '내 일정',
    title: '19일 일정',
    date: '2024-11-19',
    startTime: '10:00',
    endTime: '11:30',
    isAllDay: false,
    repeat: 'none',
    isAlarmOn: true,
    location: '회의실 A',
    memo: '회의 자료 준비',
  },
  {
    id: '2',
    category: '병원',
    title: '19일 일정',
    date: '2024-11-19',
    startTime: '12:30',
    endTime: '13:30',
    isAllDay: false,
    repeat: 'none',
    isAlarmOn: false,
    location: '근처 식당',
    memo: '',
  },
  {
    id: '3',
    category: '식사',
    title: '19일 일정',
    date: '2024-11-19',
    startTime: '18:00',
    endTime: '19:00',
    isAllDay: false,
    repeat: 'weekly',
    isAlarmOn: true,
    location: '헬스장',
    memo: '유산소 + 웨이트',
  },
  {
    id: '4',
    category: '식사',
    title: '23일 일정',
    date: '2024-11-23',
    startTime: '18:00',
    endTime: '20:00',
    isAllDay: false,
    repeat: 'weekly',
    isAlarmOn: true,
    location: '헬스장',
    memo: '유산소 + 웨이트',
  },
  {
    id: '5',
    category: '휴식',
    title: '17일 일정',
    date: '2024-11-17',
    startTime: '10:00',
    endTime: '12:00',
    isAllDay: false,
    repeat: 'weekly',
    isAlarmOn: true,
    location: '헬스장',
    memo: '유산소 + 웨이트',
  },
  {
    id: '6',
    category: '병원',
    title: '18일 일정',
    date: '2024-11-18',
    startTime: '10:00',
    endTime: '12:00',
    isAllDay: false,
    repeat: 'weekly',
    isAlarmOn: true,
    location: '헬스장',
    memo: '유산소 + 웨이트',
  },
  {
    id: '7',
    category: '휴식',
    title: '20일 일정',
    date: '2024-11-20',
    startTime: '10:00',
    endTime: '12:00',
    isAllDay: false,
    repeat: 'weekly',
    isAlarmOn: true,
    location: '헬스장',
    memo: '유산소 + 웨이트',
  },
  {
    id: '8',
    category: '병원',
    title: '21일 일정',
    date: '2024-11-21',
    startTime: '10:00',
    endTime: '12:00',
    isAllDay: false,
    repeat: 'weekly',
    isAlarmOn: true,
    location: '헬스장',
    memo: '유산소 + 웨이트',
  },
  {
    id: '9',
    category: '기타',
    title: '22일 일정',
    date: '2024-11-22',
    startTime: '10:00',
    endTime: '12:00',
    isAllDay: false,
    repeat: 'weekly',
    isAlarmOn: true,
    location: '헬스장',
    memo: '유산소 + 웨이트',
  },
  {
  id: '10',
  category: '기타',
  title: '23일 일정',
  date: '2024-11-23',
  startTime: '10:00',
  endTime: '11:10',
  isAllDay: false,
  repeat: 'weekly',
  isAlarmOn: true,
  location: '헬스장',
  memo: '유산소 + 웨이트',
  },
  {
    id: '11',
    category: '내 일정',
    title: '23일 일정',
    date: '2024-11-19',
    startTime: '00:00',
    endTime: '01:10',
    isAllDay: false,
    repeat: 'weekly',
    isAlarmOn: true,
    location: '헬스장',
    memo: '유산소 + 웨이트',
    },
];

export default mockTasks;
